#!/usr/bin/env python3
"""Tests for check_rules_size.py — run: python3 test_check_rules_size.py

A hook is code, so it ships with a test (`enforcement.md` -> Hook contracts). Both halves
matter: the must-block half proves the check fires, the must-pass half is what keeps false
positives from creeping in. A test that only ever asserts "it blocked" cannot notice the day
the hook starts blocking everything.

The hook SCANS the governed set and ignores the payload, so each scenario needs its own tree:
one over-budget file anywhere makes the whole scan speak. `CLAUDE_PROJECT_DIR` points the hook
at that tree — the hook derives the root from `__file__` otherwise, which would scan this repo.

Stdlib only, no test runner: the hook must be verifiable in a freshly scaffolded repo that
has no dev dependencies installed yet.
"""
import contextlib
import json
import os
import subprocess
import sys
import tempfile

HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "check_rules_size.py")
BUDGET = 150
GENERATED_HEADER = "<!-- GENERATED by .claude/scripts/build-inventory.py — do not edit by hand -->"

failures = []


def run(root, payload="", raw=False):
    """Feed the hook a payload (or garbage, or nothing); return (advisory_text, returncode)."""
    env = dict(os.environ, CLAUDE_PROJECT_DIR=root)
    proc = subprocess.run(
        [sys.executable, HOOK],
        input=payload if raw else json.dumps(payload) if payload else "",
        capture_output=True,
        text=True,
        env=env,
        timeout=10,  # stays below the hook's own timeout in settings.json
    )
    out = proc.stdout.strip()
    msg = json.loads(out)["hookSpecificOutput"]["additionalContext"] if out else ""
    return msg, proc.returncode


def check(name, condition, detail=""):
    print(("PASS  " if condition else "FAIL  ") + name + (f"  ({detail})" if detail and not condition else ""))
    if not condition:
        failures.append(name)


def write(root, relpath, n_lines, first_line=None):
    path = os.path.join(root, relpath.replace("/", os.sep))
    os.makedirs(os.path.dirname(path) or root, exist_ok=True)
    body = "line\n" * n_lines
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"{first_line}\n{body}" if first_line else body)
    return path


@contextlib.contextmanager
def tree(**files):
    """A throwaway project root. `files` maps a relpath -> line count, or (lines, first_line)."""
    with tempfile.TemporaryDirectory() as root:
        os.makedirs(os.path.join(root, ".claude", "rules"), exist_ok=True)
        for rel, spec in files.items():
            n, first = spec if isinstance(spec, tuple) else (spec, None)
            write(root, rel.replace("__", "/"), n, first)
        yield root


def payload(tool="Write", path=".claude/rules/over.md"):
    body = {"hook_event_name": "PostToolUse", "tool_name": tool}
    if path:
        body["tool_input"] = {"file_path": path}
    return body


def main():
    # --- must-block half: the nudge has to fire, and say something usable ---
    with tree(**{".claude__rules__over.md": BUDGET + 50}) as root:
        msg, rc = run(root, payload())
        check("over-budget rules file nudges", bool(msg), "silent")
        check("nudge reports the real line count", str(BUDGET + 50) in msg, msg[:60])
        check("nudge names the file", "over.md" in msg, msg[:60])
        check("nudge names the four options", all(w in msg for w in ("RELOCATE", "SPLIT", "ABSTRACT", "COMPRESS")), msg[:60])
        check("nudge cites the rule file it enforces", "workflow.md" in msg, msg[:60])
        check("advisory: exit code stays 0", rc == 0, f"rc={rc}")

        # The regression this hook exists to prevent: the payload must not gate the check.
        # An edit made with sed / a heredoc / a python one-liner arrives as a Bash call with
        # no file_path at all, and used to slip past in silence.
        check("Bash edit (no file_path) still nudges", bool(run(root, payload("Bash", path=None))[0]))
        check("payload naming an unrelated file still nudges", bool(run(root, payload("Write", "src/main.py"))[0]))
        check("non-JSON payload still nudges", bool(run(root, "not json at all", raw=True)[0]))
        check("empty stdin still nudges", bool(run(root)[0]))
        check("garbage payload still exits 0", run(root, "not json at all", raw=True)[1] == 0)

    with tree(**{"CLAUDE.md": BUDGET + 1}) as root:
        check("over-budget CLAUDE.md nudges", bool(run(root, payload())[0]))

    # --- generated files: the four options do not apply to them ---
    with tree(**{".claude__rules__ledger.md": (BUDGET + 50, GENERATED_HEADER)}) as root:
        msg, _ = run(root, payload())
        check("over-budget generated file nudges", bool(msg), "silent")
        check("generated file gets the generator advice", "GENERATED" in msg and "generator" in msg, msg[:80])
        check("generated file is NOT told to run the compression skill", "claude-md-improver" not in msg, msg[:80])

    with tree(**{
        ".claude__rules__ledger.md": (BUDGET + 50, GENERATED_HEADER),
        ".claude__rules__workflow.md": BUDGET + 10,
    }) as root:
        msg, _ = run(root, payload())
        check("mixed over-budget set gets both advices", "claude-md-improver" in msg and "generator" in msg, msg[:80])

    # --- must-pass half: everything below is legitimate work and must stay silent ---
    with tree(**{
        ".claude__rules__under.md": BUDGET - 50,
        ".claude__rules__edge.md": BUDGET,  # exactly at budget: still passing
        ".claude__rules__ledger.md": (BUDGET - 1, GENERATED_HEADER),
        "CLAUDE.md": BUDGET - 1,
        "src__big_module.py": BUDGET + 500,
        "docs__2026-01-01-notes.md": BUDGET + 500,
    }) as root:
        msg, rc = run(root, payload())
        check("clean governed set is silent", msg == "", msg[:80])
        check("clean tree exits 0", rc == 0, f"rc={rc}")

    # --- silence must mean exactly one thing: checked and passing ---
    with tempfile.TemporaryDirectory() as root:  # no .claude/rules, no CLAUDE.md
        msg, rc = run(root, payload())
        check("empty governed set says so instead of passing quietly", "EMPTY" in msg, msg[:80] or "silent")
        check("empty governed set still exits 0", rc == 0, f"rc={rc}")

    with tree(**{".claude__rules__ok.md": BUDGET - 1}) as root:
        os.mkdir(os.path.join(root, ".claude", "rules", "trap.md"))  # a directory, not a file
        msg, rc = run(root, payload())
        check("unreadable governed entry says so instead of passing quietly", "NOT checked" in msg, msg[:80] or "silent")
        check("unreadable governed entry still exits 0", rc == 0, f"rc={rc}")

    print()
    if failures:
        print(f"{len(failures)} FAILED: " + ", ".join(failures))
        sys.exit(1)
    print("all checks passed")


if __name__ == "__main__":
    main()
